[package]
name = "drogue-tls"
version = "0.2.0"
edition = "2018"
authors = [
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Ulf Lilleengen <lulf@redhat.com>"
]

[dependencies]
p256 = { version = "0.8.0-pre", default-features = false, features = [ "ecdh", "arithmetic" ] }
rand_core = { version = "0.6.2", default-features = false }
hkdf = "0.10.0"
hmac = "0.10.1"
sha2 = { version = "0.9.3", default-features = false }
aes-gcm = { version = "0.8.0", default-features = false, features = ["aes"] }
digest = { version = "0.9.0", default-features = false }
typenum = "1.13.0"
heapless = "0.6"
generic-array = "0.14"
nom = { version = "6.1.2", default-features = false }

# Logging alternatives
log = { version = "0.4", optional = true }
defmt = { version = "0.2", optional = true }

[dev-dependencies]
env_logger = "0.8"
tokio = { version = "1.7", features = ["full"] }
mio = { version = "0.7", features = ["os-poll", "tcp"] }
rustls = "0.19.1"
rustls-pemfile = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
log = "0.4"
embassy-net = {git = "https://github.com/embassy-rs/embassy.git", branch = "master", features = ["std", "tcp", "dhcpv4", "medium-ethernet", "log"] }
embassy = {git = "https://github.com/embassy-rs/embassy.git", branch = "master", default-features = false, features = ["std"] }
embassy-std = {git = "https://github.com/embassy-rs/embassy.git", branch = "master", default-features = false }
smoltcp = { git = "https://github.com/smoltcp-rs/smoltcp", rev="e4241510337e095b9d21136c5f58b2eaa1b78479", default-features = false }
async-io = "1.3.1"
futures = { version = "0.3.8", default-features = false, features = ["async-await"] }
libc = "0.2.81"
clap = { version = "3.0.0-beta.2", features = ["derive"] }
heapless            = { version = "0.7.1", default-features = false }

[features]
default = ["log"]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
