[package]
name = "drogue-tls"
version = "0.2.0"
edition = "2018"
authors = [
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Ulf Lilleengen <lulf@redhat.com>"
]

[dependencies]
p256 = { version = "0.8.0-pre", default-features = false, features = [ "ecdh", "arithmetic" ] }
rand_core = { version = "0.6.2", default-features = false }
hkdf = "0.10.0"
hmac = "0.10.1"
sha2 = { version = "0.9.3", default-features = false }
aes-gcm = { version = "0.8.0", default-features = false, features = ["aes"] }
digest = { version = "0.9.0", default-features = false }
typenum = "1.13.0"
heapless = "0.6"
generic-array = "0.14"
nom = { version = "6.1.2", default-features = false }

# Logging alternatives
log = { version = "0.4", optional = true }
defmt = { version = "0.2", optional = true }

# Runtimes supported out of the box
tokio = { version = "1.7", features = ["net"], optional = true }
futures = { version = "0.3", optional = true }

# NOTE: Disabled until embassy crate is published
# embassy = {git = "https://github.com/embassy-rs/embassy.git", branch = "master", default-features = false, optional = true }

[dev-dependencies]
env_logger = "0.8"
tokio = { version = "1.7", features = ["full"] }
mio = { version = "0.7", features = ["os-poll", "tcp"] }
rustls = "0.19.1"
rustls-pemfile = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
log = "0.4"

[features]
default = ["log", "std", "async", "tokio"]
std = []
async = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
